const Data = [
    {
       id: 1,
       firstName: "John",
       lastName: "Lee",
       date: "14/06/2023",
       time: "11:30",
    },
    {
        id: 2,
       firstName: "Tom",
       lastName: "John",
       date: "14/06/2023",
       time: "11:30",
    },
    {
        id: 3,
       firstName: "Jack",
       lastName: "Leornard",
       date: "14/06/2023",
       time: "11:30",
    },
    {
        id: 4,
       firstName: "Amber",
       lastName: "Thomson",
       date: "14/06/2023",
       time: "11:30",
    },
    {
        id: 5,
       firstName: "Josephine",
       lastName: "Patrick",
       date: "14/06/2023",
       time: "11:30",
    },
    {
        id: 6,
       firstName: "John",
       lastName: "Lee",
       date: "14/06/2023",
       time: "11:30",
    },
    {
        id: 7,
       firstName: "John",
       lastName: "Lee",
       date: "14/06/2023",
       time: "11:30",
    },
    {
        id: 8,
       firstName: "John",
       lastName: "Lee",
       date: "14/06/2023",
       time: "11:30",
    },
    {
        id: 9,
       firstName: "John",
       lastName: "Lee",
       date: "14/06/2023",
       time: "11:30",
    },
    {
        id: 10,
       firstName: "John",
       lastName: "Lee",
       date: "14/06/2023",
       time: "11:30",
    },
    {
        id: 11,
       firstName: "John",
       lastName: "Lee",
       date: "14/06/2023",
       time: "11:30",
    }
]
export default Data